### ISSUE TITLE
7.0 deprecations and removals

### ISSUE THREAD

**Issue by droserasprout** [dipdup-io/dipdup#583]
Just keeping track

- [ ] `pattern_config.similar_to`
- [ ] `IndexStatus` members
- [ ] `DipDupException` and `DipDupException` aliases
- [ ] Package name not in snake_case
