### ISSUE TITLE
Meta: DipDup ORM

### ISSUE THREAD

**Issue by droserasprout** [dipdup-io/dipdup#761]
Targeting 8.0

## Missing features

- [ ] Support for composite PKs.
- [ ] One-to-one and one-to-many relations in a single model (possibly works already)
- [ ] Basic TimescaleDB integration

## Bugs

- [ ] Nested transactions are broken
- [ ] Fields with null=True are typed incorrectly

## Other

- [ ] ForeignKeyField definitions should refer a single class, w/o strings
- [ ] A (much) stricter QA -- linting, typechecking etc.
- [ ] Drop ugly MySQL hacks
