### ISSUE TITLE
Meta: tech debt

### ISSUE THREAD

**Issue by droserasprout** [dipdup-io/dipdup#823]
### CLI

- [ ] Don't spam version checks

### Datasources

- [ ] Revise HttpConfig defaults
- [ ] WS connection related code copypaste

### Database

- [ ] immune_tables on SQLite require `unsafe_sqlite` flag

### EVM

- [ ] web3 integration; subscriptions, new provider
- [ ] Realtime datasource lifecycle

### Tests

- [ ] Helpers to test a single handler
- [ ] Minimize test_demos traffic
- [ ] Add test for demo_evm_events

### Docs

- [ ] cli/ctx/config references
- [ ] Missing essential docstrings
- [ ] Some DipDupError help messages are outdated

### CI

- [ ] bugs in GHA

### Code quality

- [ ] Undocumented constants (mostly sleeps)
- [ ] exceptions
- [ ] Type ignores and noqa's

### Monitoring

- [ ] prometheus
