### ISSUE TITLE
8.0 release checklist

### ISSUE THREAD

**Issue by droserasprout** [dipdup-io/dipdup#979]
## First alpha

- [x] Use  `current` branch for 7.x (`next` is still default branch)
- [x] #862
- [x] #740 (with tortoise-orm 0.20.0)
- [x] #978
- [x] #993 
- [x] #998
- [x] #1001 
- [x] Docs builder bugs
- [x] #1004 

## Beta

- [x] #933
- [x] #926
- [x] #994
- [x] Starknet support

## Stable

- [x] Release notes
- [x] Migration guide
- [x] Advanced network switcher
- [x] Release support schedule 
- [x] Check the docstrings
- [x] Update release notes
- [ ] Starknet block header flag

## Maybe

- [x] Rename demos to include blockchain name
